# Generated by Django 4.0.5 on 2022-08-18 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('summary', models.TextField(max_length=200)),
                ('genre', models.CharField(choices=[('H', 'Horror'), ('D', 'Drum'), ('A', 'Action'), ('C', 'Comedy'), ('F', 'Fantasy')], max_length=1)),
                ('director', models.CharField(max_length=20)),
                ('actors', models.CharField(max_length=500)),
                ('score', models.FloatField()),
                ('country', models.CharField(max_length=100)),
                ('yearOfPublication', models.DateField()),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('commenter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
