# Generated by Django 4.1 on 2022-08-19 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_comment_commenter_film_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='film',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.film'),
        ),
    ]
