# Generated by Django 4.0.6 on 2022-08-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='yearOfPublication',
            field=models.DateField(unique_for_year=True),
        ),
    ]
