# Generated by Django 4.0.6 on 2022-08-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_film_yearofpublication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='yearOfPublication',
            field=models.DateField(),
        ),
    ]
