# Generated by Django 4.0.6 on 2022-08-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_comment_date_alter_film_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
