# Generated by Django 4.0.6 on 2022-08-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_film_yearofpublication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.CharField(choices=[('Horror', 'Horror'), ('Drum', 'Drum'), ('Action', 'Action'), ('Comedy', 'Comedy'), ('Fantasy', 'Fantasy')], max_length=100),
        ),
    ]
