# Generated by Django 4.0.6 on 2022-09-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_comment_commenter_alter_comment_film_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='yearOfPublication',
            field=models.IntegerField(max_length=4),
        ),
    ]
