# Generated by Django 4.0.6 on 2022-09-11 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_film_yearofpublication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='yearOfPublication',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
