# Generated by Django 4.0.6 on 2022-09-13 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_customuser_full_name_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='group',
            field=models.CharField(choices=[('Anime', 'Anime'), ('Animation', 'Animation'), ('Series', 'Series'), ('Movie', 'Movie')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='yearOfPublication',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
