# Generated by Django 4.0.6 on 2022-09-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_film_group_alter_film_yearofpublication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('Horror', 'Horror'), ('Drum', 'Drum'), ('Action', 'Action'), ('Comedy', 'Comedy'), ('Fantasy', 'Fantasy')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='film',
            name='genre',
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(to='backend.genre'),
        ),
    ]
