# Generated by Django 4.0.6 on 2022-09-13 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_rename_genre_genre_genres_alter_film_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genres',
            new_name='name',
        ),
    ]
