# Generated by Django 4.0.6 on 2022-09-13 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_rename_genres_genre_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='genres',
            new_name='genre',
        ),
    ]
