# Generated by Django 4.0.6 on 2022-09-13 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_film_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='genre',
            new_name='genres',
        ),
    ]
