# Generated by Django 4.0.6 on 2022-09-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_rename_genre_film_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(related_name='genres', to='backend.genre'),
        ),
    ]
