# Generated by Django 4.0.6 on 2022-09-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_alter_film_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='average_people',
            field=models.IntegerField(null=True),
        ),
    ]
