# Generated by Django 4.0.6 on 2022-09-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_film_average_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='director',
            new_name='directors',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='name',
            new_name='pName',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='film',
            name='eName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('ترسناک', 'ترسناک'), ('درام', 'درام'), ('اکشن', 'اکشن'), ('کمدی', 'کمدی'), ('فانتزی', 'فانتزی')], max_length=20),
        ),
    ]
