# Generated by Django 4.0.6 on 2022-09-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_country_remove_film_country_film_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
