# Generated by Django 4.0.6 on 2022-09-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_film_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='directors',
            field=models.CharField(max_length=500),
        ),
    ]
