# Generated by Django 4.0.6 on 2022-09-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_alter_film_directors'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
