# Generated by Django 4.0.6 on 2022-09-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_country_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
