# Generated by Django 4.0.6 on 2022-09-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_genre_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('horror', 'horror'), ('drum', 'drum'), ('action', 'action'), ('comedy', 'comedy'), ('fantasy', 'fantasy')], max_length=20),
        ),
    ]
