# Generated by Django 4.0.6 on 2022-09-14 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_language_film_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.film')),
            ],
        ),
    ]
