# Generated by Django 4.0.6 on 2022-09-16 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_film_double_film_subtitle_film_thumbnail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='thumbnail',
            new_name='poster',
        ),
    ]
