# Generated by Django 4.0.6 on 2022-10-02 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_commentdislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivalfilm',
            name='film',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='film', to='backend.film'),
        ),
    ]
