# Generated by Django 4.0.6 on 2022-10-06 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_alter_arrivalfilm_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='favorite',
            field=models.ManyToManyField(related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
