# Generated by Django 4.0.6 on 2022-10-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_remove_profile_favorites_profile_favorites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('film_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
