# Generated by Django 4.0.6 on 2022-10-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_favorite_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FilmLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='favorite',
            name='film_eName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='film_pName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='film_photo',
            field=models.CharField(max_length=900, null=True),
        ),
    ]
