# Generated by Django 4.0.6 on 2022-10-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_filmdislike_filmlike_favorite_film_ename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='film_group',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
